service: Order
frameworkVersion: '3'

provider:
  provider:
  timeout: 900
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    HTTP_PORT: 3002
plugins:
  - serverless-offline
functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'                       
